version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build -o build/goupd cmd/main.go

  run:
    cmds:
      - task: build
      - ./build/goupd
